export const astrPreviewTextPools = {
  big: [
    'Ingredients 원재료명',
    'Nutrition facts 영양정보',
    'Synecdoche 제유법',
    'Arrivals 도착',
    'Idempotence 멱등성',
    'Entrance 입구',
    'Mise en abyme 미장아빔',
    'Paratext 곁텍스트',
    'Vanishing point 소실점',
    'Wayfinding 길찾기',
    'Concourse 탑승동',
    'Departures 출발',
    'Transfer 환승',
    'Emergency exit 비상구',
    'Latent space 잠재 공간',
    'Tokenization 토큰화',
    'Hallucination 환각',
    'Backpropagation 역전파',
    'Hysteresis 이력 현상',
    'Orthogonality 직교성',
    'Affordance 행동 유도성',
  ],
  mid: [
    '1948년 세계인권선언(UDHR) 제1조: 모든 인간은 태어날 때부터 자유로우며 그 존엄과 권리에 있어 동등하다.',
    '대한민국 헌법 제1조 1·2항: 대한민국은 민주공화국이다. 대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다.',
    '보고 계십니까, 들리십니까! 당신이 꿈꾸어 왔던 그 순간! 2011년 챔피언! 삼성 라이온즈입니다!',
    '1972년 11월 21일, 김두한은 오랜 지병이었던 고혈압으로 쓰러졌다.',
    '걔는 진짜 딱 오잖아? 지 혼자! 이렇게 해 가지고, 진짜! 이러면서 막 새치기하면서 들어가고! 뭔 느낌인지 알죠?',
    '니 하는 플레이보이 예전에 하더 놈 같은데, 이제 얼굴 까고 하는갑지. 돈 좀 버냐? 개노잼. 놀아라?',
    '아까도 그 5/5 도발 왜 하냐고 아주 그냥 눈 뒤집어 까가… 5/5 도발 왜, 왜 하냐고.',
    '그러니까 내가 누군가를 이제 좋아한다는 사실이 그 사람에게는 상처가 될 수도 있잖아요…',
    'KTX 103편은 폐색 구간 B에 진입한 뒤 다음 신호가 진행으로 바뀔 때까지 정차합니다.',
    '이 역은 열차와 승강장 사이가 넓으니 내리실 때 조심하시기 바랍니다.',
    'A17 게이트는 21:40에 닫히며, KE 231편은 21:55에 출발합니다.',
    'HTTP 429: 요청이 너무 많습니다 — 60초 뒤에 다시 시도하십시오.',
  ],
} as const
