import type {ElementContent} from 'hast'
import type {Node, Text} from 'mdast'
import rehypeStringify from 'rehype-stringify'
import {remark} from 'remark'
import remarkCjkFriendly from 'remark-cjk-friendly'
import remarkCjkFriendlyGfmStrikethrough from 'remark-cjk-friendly-gfm-strikethrough'
import remarkGfm from 'remark-gfm'
import remarkRehype from 'remark-rehype'
import remarkRuby from 'remark-ruby'
import smartypants from 'remark-smartypants'
import strip from 'strip-markdown'
import {stripLanguageTemplates} from './language-template.ts'

interface RubyNode extends Node {
  type: 'ruby'
  data: {hChildren: ElementContent[]}
}

declare module 'mdast' {
  interface RootContentMap {
    ruby: RubyNode
  }
  interface PhrasingContentMap {
    ruby: RubyNode
  }
}

function fallbackText(nodes: ElementContent[]): string {
  return nodes
    .map((node) => (node.type === 'text' ? node.value : node.type === 'element' ? fallbackText(node.children) : ''))
    .join('')
}

function stripRuby(node: RubyNode): Text {
  // Include the <rp> fallback parentheses already generated by remark-ruby.
  return {type: 'text', value: fallbackText(node.data.hChildren)}
}

// --- Reusable remark processors ---
// Processors are frozen via .freeze() on first use, so creating them once is efficient.

/** Strips markdown to plain text and applies smartypants for title processing. */
export const titleProcessor = remark().use(strip).use(smartypants, {dashes: 'oldschool'})

/** Strips markdown (with GFM support) to plain text for description generation. */
export const descriptionProcessor = remark()
  .use(remarkGfm)
  .use(remarkCjkFriendly)
  .use(remarkCjkFriendlyGfmStrikethrough)
  .use(strip, {remove: [['ruby', stripRuby]]})
  .use(smartypants, {dashes: 'oldschool'})

// Parse ruby without using its Markdown serializer, which also escapes ordinary braces.
const descriptionParser = descriptionProcessor().use(remarkRuby)

/** Renders markdown to HTML (no directives — used for simple content like software-stack). */
export const simpleHtmlProcessor = remark()
  .use(remarkGfm)
  .use(remarkCjkFriendly)
  .use(smartypants, {dashes: 'oldschool'})
  .use(remarkRehype)
  .use(rehypeStringify)

// --- Shared helper functions ---

/** Processes a title string: strips markdown formatting and removes newlines. */
export async function processTitle(title: string): Promise<string> {
  return (await titleProcessor.process(stripLanguageTemplates(title))).toString().replaceAll('\n', '')
}

/** Generates a description from raw markdown content (max 200 chars + ellipsis). */
export async function generateDescription(content: string): Promise<string> {
  const tree = descriptionParser.parse(stripLanguageTemplates(content))
  const plainTextTree = await descriptionProcessor.run(tree)
  const stripped = descriptionProcessor
    .stringify(plainTextTree)
    .replaceAll('\n', ' ')
    .replaceAll('  ', ' ')
    .replaceAll('\\~', '~')
    .replaceAll(/:::figure\{[\s\S]*?\}\n?([\s\S]*?)\n?:::/g, '$1')
    .replaceAll(/::figure\{[\s\S]*?\}/g, '')
    .trim()

  return stripped.length > 250 ? stripped.substring(0, 250).trim() + '\u2026' : stripped
}
