name = "quiple-blog"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
workers_dev = false
preview_urls = false

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true

[limits]
cpu_ms = 30000

[[r2_buckets]]
binding = "R2"
bucket_name = "blog"
