import {readFile, readdir, realpath, writeFile} from 'node:fs/promises'
import {dirname, join, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const json = async (path) => JSON.parse(await readFile(path, 'utf8'))
const project = await json(join(root, 'package.json'))
const visited = new Set()
const packages = new Map()
const texts = new Map()

async function locate(name, from) {
  for (let directory = from; ; directory = dirname(directory)) {
    try {
      return await realpath(join(directory, 'node_modules', name))
    } catch (error) {
      if (error.code !== 'ENOENT' && error.code !== 'ENOTDIR') throw error
    }
    if (dirname(directory) === directory) return undefined
  }
}

async function legalFiles(directory, nested = false) {
  const result = []
  for (const entry of await readdir(directory, {withFileTypes: true})) {
    const path = join(directory, entry.name)
    if (entry.isFile() && (nested || /^(licen[cs]e|copying|notice|copyright)([._-]|$)/i.test(entry.name))) {
      const text = await readFile(path, 'utf8')
      if (!text.includes('\0')) result.push(text)
    } else if (entry.isDirectory() && (nested || /^licen[cs]es$/i.test(entry.name))) {
      result.push(...(await legalFiles(path, true)))
    }
  }
  return result
}

async function collect(name, from, required = false) {
  const directory = await locate(name, from)
  if (!directory) {
    if (required) throw new Error(`Install dependencies before generating notices: ${name}`)
    return
  }
  if (visited.has(directory)) return
  visited.add(directory)
  const pkg = await json(join(directory, 'package.json'))
  const id = `${pkg.name}@${pkg.version}`
  const entry = packages.get(id) ?? {
    license: typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'Not declared'),
    notices: new Set(),
  }
  for (const text of await legalFiles(directory)) {
    const hash = createHash('sha256').update(text).digest('hex')
    texts.set(hash, text)
    entry.notices.add(hash)
  }
  packages.set(id, entry)
  for (const dependency of Object.keys({
    ...pkg.dependencies,
    ...pkg.optionalDependencies,
    ...pkg.peerDependencies,
  }).sort()) {
    await collect(dependency, directory)
  }
}

for (const name of Object.keys({...project.dependencies, ...project.devDependencies}).sort())
  await collect(name, root, true)
const hashes = [...texts.keys()].sort((a, b) => a.localeCompare(b, 'en'))
const numbers = new Map(hashes.map((hash, index) => [hash, index + 1]))
const escapeCell = (text) => text.replaceAll('|', '\\|').replaceAll('\n', ' ')
const output = [
  '# Third-party software notices',
  '',
  'Generated by `nub run licenses` from the installed dependency tree. Includes development tools, installed optional packages and peer dependencies. Other operating systems may install additional packages; regenerate for each distribution environment.',
  '',
  'These packages retain their own licenses and copyright notices. The project’s AGPL-3.0-only license does not replace them. License metadata is reported as supplied by each package, not independently classified.',
  '',
  'This inventory covers npm packages only. Fonts, BDF files, content, artwork, trademarks, and third-party source copied into the repository require their own notices and permissions. An absent notice below is not a grant of permission; review the upstream package before redistribution.',
  '',
  'AMLL source: https://github.com/amll-dev/applemusic-like-lyrics (core and TTML packages: AGPL-3.0-only). Project integration changes are maintained in scripts/amll/ and src/lib/lyrics/document-player.ts and src/lib/components/lyrics/.',
  '',
  '| Package | Declared license | Bundled notices |',
  '| --- | --- | --- |',
]
for (const [id, entry] of [...packages].sort(([a], [b]) => a.localeCompare(b, 'en'))) {
  const links = [...entry.notices].map((hash) => `[${numbers.get(hash)}](#notice-${numbers.get(hash)})`).join(', ')
  output.push(`| ${escapeCell(id)} | ${escapeCell(entry.license)} | ${links || 'Not included in installed package'} |`)
}
for (const hash of hashes) {
  const text = texts.get(hash)
  const longest = Math.max(2, ...[...text.matchAll(/`+/g)].map((match) => match[0].length))
  const fence = '`'.repeat(longest + 1)
  output.push('', `## Notice ${numbers.get(hash)}`, '', fence + 'text', text, fence)
}
await writeFile(join(root, 'THIRD_PARTY_NOTICES.md'), output.join('\n') + '\n')
console.log(`Generated notices for ${packages.size} package versions (${texts.size} distinct notice texts).`)
